### PR TITLE
Remove old config options

### PR DESCRIPTION
**Pull request by albertrdixon**
@lumoslabs/devops 

Remove eliminated configuration options

### CODE REVIEW

**Comment by srhaber** [comment]
👍 if tested

**Comment by albertrdixon** [comment]
These config options were eliminated in `5.x` and are now causing fatal errors if present in the config file

**Comment by albertrdixon** [comment]
lots of changes actually:  As suggested in upgrade documents I ran `shorewall update` which converted the `shorewall.conf` to `5.x.x` format & options

**Comment by srhaber** [comment]
Is there a shorewall 5.x cookbook out in the wild, or should we proceed with maintaining this now heavily-forked cookbook?

**Comment by albertrdixon** [comment]
The maintained cookbook is [firewall](https://supermarket.chef.io/cookbooks/firewall) (from chef) which configures iptables rules directly.

`shorewall_reloaded` is the most recent, but has been essentially abandoned since 2015.

I think using this is fine for now, but we should bump the priority for moving away from shorewall and using iptables directly.

**Pull request merged**
